import React, { useState } from "react";
import { PitchResult } from "../types";
import {
  Copy,
  Check,
  Mail,
  Quote,
  Target,
  ArrowRight,
  ExternalLink,
  Download,
  FileText,
} from "lucide-react";

interface PitchResultCardsProps {
  result: PitchResult;
}

export const PitchResultCards: React.FC<PitchResultCardsProps> = ({
  result,
}) => {
  const [copiedSubject, setCopiedSubject] = useState(false);
  const [copiedEmail, setCopiedEmail] = useState(false);
  const [copiedCta, setCopiedCta] = useState(false);
  const [downloadedTxt, setDownloadedTxt] = useState(false);

  const subjectLine = result.subjectLine || result.subject_line || "";
  const hookThesis = result.hookThesis || result.angle_title || "";
  const emailBody = result.emailBody || result.email_body || "";
  const evidencePoints: string[] =
    Array.isArray(result.keyEvidencePoints) && result.keyEvidencePoints.length > 0
      ? result.keyEvidencePoints
      : result.evidence_snippet
      ? [result.evidence_snippet]
      : [];
  const cta =
    result.call_to_action ||
    "Would you be open to a quick 10-minute chat this week to explore this?";

  const fullEmailContent = `Subject: ${subjectLine}\n\n${emailBody}\n\n${cta}`;

  const copyToClipboard = async (
    text: string,
    type: "subject" | "email" | "cta",
  ) => {
    try {
      await navigator.clipboard.writeText(text);
      if (type === "subject") {
        setCopiedSubject(true);
        setTimeout(() => setCopiedSubject(false), 2000);
      } else if (type === "email") {
        setCopiedEmail(true);
        setTimeout(() => setCopiedEmail(false), 2000);
      } else if (type === "cta") {
        setCopiedCta(true);
        setTimeout(() => setCopiedCta(false), 2000);
      }
    } catch {
      // Fallback for restricted clipboard iframe environments
      const textArea = document.createElement("textarea");
      textArea.value = text;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand("copy");
      document.body.removeChild(textArea);
      if (type === "subject") setCopiedSubject(true);
      if (type === "email") setCopiedEmail(true);
      if (type === "cta") setCopiedCta(true);
      setTimeout(() => {
        setCopiedSubject(false);
        setCopiedEmail(false);
        setCopiedCta(false);
      }, 2000);
    }
  };

  const handleDownloadTxt = () => {
    const formattedDate = new Date().toISOString().replace(/[:.]/g, "-");
    const formattedEvidence =
      evidencePoints.length > 0
        ? evidencePoints.map((p, i) => `  ${i + 1}. "${p}"`).join("\n")
        : `  "${result.evidence_snippet || ""}"`;

    const content = `================================================================================
PITCHHOOK OUTREACH PITCH
Generated: ${new Date().toLocaleString()}
================================================================================

HOOK THESIS:
${hookThesis}

KEY EVIDENCE POINTS (STRICTLY FROM COMPANY TEXT):
${formattedEvidence}

MUTUAL VALUE RATIONALE:
${result.rationale || hookThesis}

--------------------------------------------------------------------------------
EMAIL SUBJECT LINE:
${subjectLine}
--------------------------------------------------------------------------------

EMAIL BODY:
${emailBody}

CALL TO ACTION:
${cta}

================================================================================
Generated by PitchHook • Evidence-based cold outreach
================================================================================`;

    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    const sanitizedTitle = hookThesis
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .slice(0, 24);
    link.href = url;
    link.download = `pitchhook-${sanitizedTitle || "pitch"}-${formattedDate}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setDownloadedTxt(true);
    setTimeout(() => setDownloadedTxt(false), 2000);
  };

  const handleOpenEmailClient = () => {
    const mailto = `mailto:?subject=${encodeURIComponent(subjectLine)}&body=${encodeURIComponent(
      `${emailBody}\n\n${cta}`,
    )}`;
    window.location.href = mailto;
  };

  return (
    <div className="space-y-4 pt-2" id="pitch-results-container">
      {/* Top Action Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2.5 pb-1">
        <h2 className="text-xs sm:text-sm font-bold uppercase tracking-widest text-[#7A7169] dark:text-[#A8A199] flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-[#3E5C52] inline-block"></span>
          Generated Pitch Analysis
        </h2>

        {/* Quick 1-Click Action Group */}
        <div className="flex items-center flex-wrap gap-2">
          {/* 1-Click Copy Full Email */}
          <button
            type="button"
            onClick={() => copyToClipboard(fullEmailContent, "email")}
            id="quick-copy-full-email-btn"
            className={`text-xs font-bold px-3 py-1.5 rounded-xl border flex items-center gap-1.5 transition-all shadow-xs cursor-pointer ${
              copiedEmail
                ? "bg-[#3E5C52] border-[#3E5C52] text-white"
                : "bg-white dark:bg-[#1E2824] border-[#E0D7D0] dark:border-[#2C3933] text-[#3E5C52] dark:text-[#7BA597] hover:bg-[#F0F7F4] dark:hover:bg-[#23352E]"
            }`}
            title="Copy subject line, body, and CTA to clipboard"
          >
            {copiedEmail ? (
              <>
                <Check className="w-3.5 h-3.5" />
                <span>Copied Full Email!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Full Email</span>
              </>
            )}
          </button>

          {/* Quick Copy Subject */}
          <button
            type="button"
            onClick={() => copyToClipboard(subjectLine, "subject")}
            id="quick-copy-subject-btn"
            className={`text-xs font-semibold px-2.5 py-1.5 rounded-xl border flex items-center gap-1.5 transition-all shadow-xs cursor-pointer ${
              copiedSubject
                ? "bg-[#3E5C52] border-[#3E5C52] text-white font-bold"
                : "bg-white dark:bg-[#1E2824] border-[#E0D7D0] dark:border-[#2C3933] text-[#7A7169] dark:text-[#A8A199] hover:text-[#1B2B24] dark:hover:text-[#EDEAE5] hover:bg-[#FAF9F7] dark:hover:bg-[#18221E]"
            }`}
            title="Copy subject line only"
          >
            {copiedSubject ? (
              <>
                <Check className="w-3.5 h-3.5" />
                <span>Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Subject</span>
              </>
            )}
          </button>

          {/* Export / Download as .txt */}
          <button
            type="button"
            onClick={handleDownloadTxt}
            id="export-txt-btn"
            className={`text-xs font-semibold px-2.5 py-1.5 rounded-xl border flex items-center gap-1.5 transition-all shadow-xs cursor-pointer ${
              downloadedTxt
                ? "bg-[#3E5C52] border-[#3E5C52] text-white font-bold"
                : "bg-white dark:bg-[#1E2824] border-[#E0D7D0] dark:border-[#2C3933] text-[#7A7169] dark:text-[#A8A199] hover:text-[#1B2B24] dark:hover:text-[#EDEAE5] hover:bg-[#FAF9F7] dark:hover:bg-[#18221E]"
            }`}
            title="Export full pitch as formatted .txt file"
          >
            {downloadedTxt ? (
              <>
                <Check className="w-3.5 h-3.5" />
                <span>Downloaded .txt!</span>
              </>
            ) : (
              <>
                <Download className="w-3.5 h-3.5" />
                <span>Export .txt</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Card 1: Hook Thesis and Extracted Key Evidence Points */}
      <div
        id="card-hook-evidence"
        className="rounded-2xl border border-[#E0D7D0] dark:border-[#2C3933] bg-white dark:bg-[#1E2824] p-4 sm:p-5 shadow-xs space-y-4"
      >
        <div className="flex items-start justify-between gap-3">
          <div>
            <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-md text-[10px] sm:text-xs font-bold uppercase tracking-wider bg-[#F0F7F4] dark:bg-[#23352E] text-[#3E5C52] dark:text-[#7BA597] border border-[#3E5C52]/20">
              <Target className="w-3 h-3" />
              Hook Thesis
            </span>
            <h3 className="text-base sm:text-lg font-bold text-[#1B2B24] dark:text-[#EDEAE5] mt-2 leading-snug">
              {hookThesis}
            </h3>
          </div>
        </div>

        {/* Key Evidence Points extracted strictly from target company copy */}
        <div className="space-y-2">
          <div className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-widest text-[#7A7169] dark:text-[#A8A199]">
            <Quote className="w-3 h-3 text-[#3E5C52] dark:text-[#7BA597]" />
            Key Evidence Points ({evidencePoints.length})
          </div>

          <div className="grid grid-cols-1 gap-2.5">
            {evidencePoints.map((point, index) => (
              <div
                key={index}
                className="flex items-start gap-2.5 p-3 bg-[#FAF9F7] dark:bg-[#18221E] rounded-xl border border-[#E0D7D0] dark:border-[#2C3933]"
              >
                <span className="w-5 h-5 rounded-full bg-[#3E5C52]/10 dark:bg-[#3E5C52]/20 text-[#3E5C52] dark:text-[#7BA597] flex items-center justify-center text-[10px] font-bold shrink-0 mt-0.5">
                  {index + 1}
                </span>
                <p className="text-xs leading-relaxed italic text-[#5C544E] dark:text-[#C5BEB7] select-all">
                  &ldquo;{point}&rdquo;
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Card 2: Outreach Subject Line with 1-Click Copy */}
      <div
        id="card-subject-line"
        className="rounded-2xl border border-[#E0D7D0] dark:border-[#2C3933] bg-white dark:bg-[#1E2824] p-4 sm:p-5 shadow-xs"
      >
        <div className="flex items-center justify-between mb-1.5">
          <span className="text-xs font-bold uppercase tracking-widest text-[#7A7169] dark:text-[#A8A199]">
            Subject Line
          </span>
          <button
            type="button"
            onClick={() => copyToClipboard(subjectLine, "subject")}
            id="copy-subject-btn"
            className={`text-xs font-semibold px-2.5 py-1 rounded-lg border transition-all flex items-center gap-1.5 cursor-pointer ${
              copiedSubject
                ? "bg-[#3E5C52] border-[#3E5C52] text-white font-bold"
                : "border-[#E0D7D0] dark:border-[#2C3933] text-[#7A7169] dark:text-[#A8A199] hover:text-[#1B2B24] dark:hover:text-[#EDEAE5] hover:bg-[#FAF9F7] dark:hover:bg-[#18221E]"
            }`}
            title="Copy subject line"
          >
            {copiedSubject ? (
              <>
                <Check className="w-3.5 h-3.5" />
                <span>Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Subject</span>
              </>
            )}
          </button>
        </div>
        <p className="text-base sm:text-lg font-semibold text-[#1B2B24] dark:text-[#EDEAE5] select-all">
          {subjectLine}
        </p>
      </div>

      {/* Card 3: Ready-to-Send 3-Paragraph Pitch Email Draft */}
      <div
        id="card-email-body"
        className="rounded-2xl border border-[#E0D7D0] dark:border-[#2C3933] bg-white dark:bg-[#1E2824] p-4 sm:p-5 shadow-xs space-y-3"
      >
        <div className="flex items-center justify-between pb-2 border-b border-[#F0EBE6] dark:border-[#2C3933]">
          <div className="flex items-center gap-2">
            <Mail className="w-4 h-4 text-[#3E5C52] dark:text-[#7BA597]" />
            <span className="text-xs font-bold uppercase tracking-widest text-[#7A7169] dark:text-[#A8A199]">
              Pitch Email Draft (3 Paragraphs)
            </span>
          </div>
          <button
            type="button"
            onClick={() => copyToClipboard(fullEmailContent, "email")}
            id="copy-full-email-btn"
            className={`text-xs font-bold px-3 py-1.5 rounded-lg flex items-center gap-1.5 transition-all shadow-xs cursor-pointer ${
              copiedEmail
                ? "bg-[#2F463E] text-white"
                : "bg-[#3E5C52] hover:bg-[#2F463E] text-white"
            }`}
            title="Copy full email draft ready to send"
          >
            {copiedEmail ? (
              <>
                <Check className="w-3.5 h-3.5" />
                <span>Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Full Email</span>
              </>
            )}
          </button>
        </div>

        {/* Clean render of the email text preserving whitespace/paragraphs */}
        <div className="text-xs sm:text-sm text-[#1B2B24] dark:text-[#EDEAE5] leading-relaxed bg-[#FAF9F7] dark:bg-[#18221E] p-4 border border-[#F0EBE6] dark:border-[#2C3933] rounded-xl whitespace-pre-line select-all space-y-3 font-normal">
          {emailBody}
        </div>
      </div>

      {/* Card 4: Low-Friction Call to Action (CTA) */}
      <div
        id="card-call-to-action"
        className="rounded-2xl border border-[#3E5C52]/20 bg-[#3E5C52]/5 dark:bg-[#3E5C52]/15 p-4 sm:p-5 shadow-xs"
      >
        <div className="flex items-center justify-between mb-2">
          <span className="text-xs font-bold uppercase tracking-wider text-[#3E5C52] dark:text-[#7BA597] flex items-center gap-1.5">
            <ArrowRight className="w-3.5 h-3.5" />
            Next Step: Low-Friction CTA
          </span>
          <button
            type="button"
            onClick={() => copyToClipboard(cta, "cta")}
            id="copy-cta-btn"
            className={`text-xs font-semibold px-2.5 py-1 rounded-lg border transition-all flex items-center gap-1.5 cursor-pointer ${
              copiedCta
                ? "bg-[#3E5C52] border-[#3E5C52] text-white font-bold"
                : "border-[#3E5C52]/30 text-[#3E5C52] dark:text-[#7BA597] hover:bg-[#3E5C52]/10"
            }`}
            title="Copy CTA"
          >
            {copiedCta ? (
              <>
                <Check className="w-3.5 h-3.5" />
                <span>Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy CTA</span>
              </>
            )}
          </button>
        </div>
        <p className="text-sm sm:text-base font-semibold text-[#1B2B24] dark:text-[#EDEAE5] select-all">
          {cta}
        </p>
      </div>

      {/* Bottom Export & Mailto Actions */}
      <div className="pt-1 pb-4 flex flex-wrap items-center justify-center gap-2.5">
        <button
          type="button"
          onClick={handleDownloadTxt}
          id="bottom-export-txt-btn"
          className="text-xs text-[#1B2B24] dark:text-[#EDEAE5] hover:text-[#3E5C52] dark:hover:text-[#7BA597] flex items-center gap-1.5 py-2 px-3.5 rounded-xl border border-[#E0D7D0] dark:border-[#2C3933] bg-white dark:bg-[#1E2824] hover:bg-[#FAF9F7] dark:hover:bg-[#23352E] transition-colors cursor-pointer shadow-xs font-semibold"
        >
          <FileText className="w-3.5 h-3.5 text-[#3E5C52] dark:text-[#7BA597]" />
          <span>{downloadedTxt ? "Downloaded as .txt!" : "Download as .txt"}</span>
        </button>

        <button
          type="button"
          onClick={handleOpenEmailClient}
          id="open-mail-app-btn"
          className="text-xs text-[#7A7169] dark:text-[#A8A199] hover:text-[#3E5C52] dark:hover:text-[#7BA597] flex items-center gap-1.5 py-2 px-3.5 rounded-xl border border-[#E0D7D0] dark:border-[#2C3933] bg-white/70 dark:bg-[#1E2824]/70 hover:bg-white dark:hover:bg-[#1E2824] transition-colors cursor-pointer"
        >
          <ExternalLink className="w-3.5 h-3.5" />
          <span>Open in default mail app</span>
        </button>
      </div>
    </div>
  );
};

